backbone:
  - [-1, nn.Identity, []]
  - [0, GetRGBModalityTensor, []]
  - [0, GetNPYModalityTensor, []]
  - [1, StemBlock, [16, 16, True]]
  - [-1, HG_Stage, [16, 64, 1, 3, False, False, 3, True, 'se']]
  - [-1, HG_Stage, [32, 256, 1, 3, True, False, 3, True, 'se']]
  - [2, StemBlock, [16, 16, True]]
  - [-1, HG_Stage, [16, 32, 1, 1, False, False, 3, True, 'se']]
  - [-1, HG_Stage, [32, 128, 1, 1, True, False, 3, True, 'se']]
  - [[5, 8], Concat, []]
  - [-1, HG_Stage, [64, 512, 2, 3, True, True, 5, True, 'se']]
  - [8, HG_Stage, [64, 256, 1, 1, True, True, 5, True, 'se']]
  - [[10, 11], Concat, []]
  - [-1, HG_Stage, [128, 1024, 1, 3, True, True, 5, True, 'se']]
  - [11, HG_Stage, [128, 512, 1, 1, True, True, 5, True, 'se']]
  - [[13, 14], Concat, []]

encoder:
  - [12, ConvNormLayer_fuse, [128, 1, 1]]
  - [15, ConvNormLayer_fuse, [128, 1, 1]]
  - [-1, TransformerEncoderBlock, [8, 512, 0.1, "relu", 10000, False]]
  - [-1, ConvNormLayer_fuse, [128, 1, 1]]
  - [-1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 12], Concat, []]
  - [-1, RepNCSPELAN4, [128, 256, 21, 2, False, 'silu']]
  - [-1, MaxSigmoidAttnBlock, [128, 1, 128]]
  - [-1, SCDown, [128, 3, 2, 'silu']]
  - [[-1, 19], Concat, []]
  - [-1, RepNCSPELAN4, [128, 256, 21, 2, False, 'silu']]
  - [-1, MaxSigmoidAttnBlock, [128, 1, 128]]

decoder:
  - [[23, 27], TGFAOVDFINETransformer, {"feat_strides":[16, 32], "hidden_dim":128, "num_levels":2, "num_layers":3, "num_points":[6, 6], "dim_feedforward":512, "text_nhead":4}]
